---
- name: Import all scripts
  hosts: all
  gather_facts: no
  become: yes

  vars:
   source_file: /home/minimal/ansible/Progress
   autostart_path: /linuxcash/cash/conf/autostart
   flags_path: /root/flags
   cron_path: /etc/cron.d

  tasks:
#  - name: Copy in autostart
#    copy: src={{ source_file }}/lock_caps.sh dest={{ autostart_path }} mode=755
#    ignore_errors: yes

  - name: Copy in flags
    copy: src={{ source_file }}/{{ item }} dest={{ flags_path }} mode=755
    with_items:
#     - "clearcashe.sh"
#     - "rtkStatus.sh"
     - "mysqldump.sh"
#    copy: src={{ source_file }}/clearcache.sh dest={{ flags_path }} mode=755
#  - copy: src={{ source_file }}/rtkStatus.sh  dest={{ flags_path }} mode=755
#  - copy: src={{ source_file }}/mysqldump.sh  dest={{ flags_path }} mode=755
    ignore_errors: yes

  - name: Copy in root
    copy: src={{ source_file }}/{{ item }} dest=/root mode=755
    with_items:
#     - "resendPivo"
#     - "Cheki"
#     - "white420"
     - "AutoSQL"
#     - "checkError.sh"
#     - "cashData.sh"
     - "restoreMysqlDump.sh"
     - "queryResTTNs"
    ignore_errors: yes

  - name: Copy in cron.d
    copy: src={{ source_file }}/cron/{{ item }} dest={{ cron_path }} mode=644
    with_items:
      - "requestTTN"
      - "mysqldump"
#      - "checkError"
      - "autoSQL"
#      - "clearcache"
    ignore_errors: yes
   
